//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesSet
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ManagerId { get; set; }
        public int ClientId { get; set; }
        public int GoodsId { get; set; }
        public double Cost { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual GoodsSet GoodsSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
    }
}
